import {
  checkWhenVisible,
  clearWhenVisible,
  clickOpensNewPage,
  clickWhenVisible,
  closePage,
  doubleClickWhenVisible,
  expectChecked,
  expectContainsText,
  expectCount,
  expectCountGreaterThan,
  expectDisabled,
  expectEnabled,
  expectFocused,
  expectHidden,
  expectPageTitle,
  expectSelected,
  expectText,
  expectUnchecked,
  expectValue,
  expectVisible,
  fill,
  fillWhenVisible,
  getTextWhenVisible,
  goBack,
  hoverWhenVisible,
  longPressWhenVisible,
  navigateTo,
  scrollIntoView,
  scrollIntoViewWhenVisible,
  selectOptionWhenVisible,
  takeScreenshot,
  typeTextWhenVisible,
  uncheckWhenVisible,
  waitForHidden,
  waitForNewPage,
  waitForVisible,
  waitMs,
  webLocator,
} from "../support/web-actions";

// Auto-generated by Autonix Recorder — regenerated in full on every save
// that touches a Salesforce object. Do not hand-edit; changes will be lost.
export type SfFieldLocatorSpec = WebLocatorSpec & { actionKind: string; sfFieldApiName?: string | null };

export class SalesforceDataPage {
  constructor(private readonly page: Page) {}

  /** Auto-generated from the Lead object's Salesforce schema. Reference fields
   *  get a live-fetched sample Id (re-queried every call, never stale); Picklist fields get
   *  the schema's default (or first active) value. Anything else we can't safely fake is
   *  left commented out — fill in a valid value before use. */
  async generateLeadData() {
    return {
      AnnualRevenue: dataUtils.float(),
      City: dataUtils.city(),
      Company: dataUtils.companyName(), // required
      CompanyDunsNumber: dataUtils.words(2),
      Country: dataUtils.country(),
      CurrentGenerators__c: dataUtils.words(2),
      DandbCompanyId: await this.fetchSampleId('DandBCompany'), // auto-fetched sample DandBCompany Id
      Description: dataUtils.paragraph(),
      Email: dataUtils.email(),
      Fax: dataUtils.phone(),
      FirstName: dataUtils.firstName(),
      IndividualId: await this.fetchSampleId('Individual'), // auto-fetched sample Individual Id
      IsConverted: dataUtils.bool(), // required
      IsUnreadByOwner: dataUtils.bool(), // required
      Jigsaw: dataUtils.words(2),
      LastName: dataUtils.lastName(), // required
      Latitude: dataUtils.float(),
      Longitude: dataUtils.float(),
      MobilePhone: dataUtils.phone(),
      NumberOfEmployees: dataUtils.number(),
      NumberofLocations__c: dataUtils.float(),
      OwnerId: await this.fetchSampleId('Group'), // required — auto-fetched sample Group Id, replace if it doesn't suit your test
      Phone: dataUtils.phone(),
      PostalCode: dataUtils.zipCode(),
      SICCode__c: dataUtils.words(2),
      State: dataUtils.state(),
      // Status: TODO — Picklist, required — provide a valid value
      Street: dataUtils.paragraph(),
      Title: dataUtils.jobTitle(),
      Website: dataUtils.httpsUrl(),
    };
  }

  private static fieldLookup(locators: Record<string, SfFieldLocatorSpec>): Map<string, SfFieldLocatorSpec> {
    const lookup = new Map<string, SfFieldLocatorSpec>();
    for (const spec of Object.values(locators)) {
      if (!spec.sfFieldApiName || lookup.has(spec.sfFieldApiName)) continue; // first schema-verified match wins
      lookup.set(spec.sfFieldApiName, spec);
    }
    return lookup;
  }

  /** Fill one or more Salesforce fields by API name in a single call — resolves to the
   *  right widget (text/picklist/checkbox) automatically. Unmapped fields throw so a typo
   *  in a field name fails the test instead of silently doing nothing. A field left `null`
   *  (e.g. generateXData() couldn't find a live sample Id for a Reference field) is skipped
   *  the same as `undefined`, rather than being coerced into a broken "null" string value. */
  async fillFields(locators: Record<string, SfFieldLocatorSpec>, data: Partial<Record<string, string | boolean | null>>): Promise<void> {
    const lookup = SalesforceDataPage.fieldLookup(locators);
    for (const [field, value] of Object.entries(data)) {
      if (value === undefined || value === null) continue;
      const spec = lookup.get(field);
      if (!spec) throw new Error(`fillFields: no schema-verified field "${field}" among the given locators`);
      const loc = webLocator(this.page, spec);
      switch (spec.actionKind) {
        case 'textbox':
          await fillWhenVisible(loc, String(value));
          break;
        case 'checkbox':
          if (value === true || value === 'true') await checkWhenVisible(loc); else await uncheckWhenVisible(loc);
          break;
        case 'combobox':
          await selectOptionWhenVisible(loc, String(value));
          break;
        case 'radio':
          await clickWhenVisible(loc);
          break;
        case 'switch': {
          const isOn = (await loc.getAttribute('aria-checked')) === 'true';
          if ((value === true || value === 'true') !== isOn) await clickWhenVisible(loc);
          break;
        }
        default:
          throw new Error(`fillFields: field "${field}" has no fillable widget (actionKind "${spec.actionKind}")`);
      }
    }
  }

  /** Read a Salesforce field's current displayed value by API name. */
  async getFieldValue(locators: Record<string, SfFieldLocatorSpec>, field: string): Promise<string> {
    const spec = SalesforceDataPage.fieldLookup(locators).get(field);
    if (!spec) throw new Error(`getFieldValue: no schema-verified field "${field}" among the given locators`);
    const loc = webLocator(this.page, spec);
    switch (spec.actionKind) {
      case 'textbox':
      case 'text':
        return getTextWhenVisible(loc);
      case 'checkbox':
        return String(await loc.isChecked());
      case 'switch':
        return String((await loc.getAttribute('aria-checked')) === 'true');
      default:
        throw new Error(`getFieldValue: field "${field}" has no readable value (actionKind "${spec.actionKind}")`);
    }
  }

  /** Queries one real, currently-valid record Id for the given object — used by the
   *  generateXData() methods above to fill Reference fields (e.g. OwnerId) with something
   *  that actually exists, re-queried on every call so it never goes stale. Same same-origin,
   *  session-riding fetch every other Salesforce call in this file already relies on — no
   *  separate credentials. Fails closed: no permission, zero records, or a network error all
   *  resolve to null rather than a broken/guessed value. */
  async fetchSampleId(objectApiName: string): Promise<string | null> {
    return this.page.evaluate(async (objectApiName) => {
      try {
        const soql = encodeURIComponent(`SELECT Id FROM ${objectApiName} LIMIT 1`);
        const res = await fetch(`/services/data/v61.0/query?q=${soql}`, { credentials: 'include', headers: { Accept: 'application/json' } });
        if (!res.ok) return null;
        const data = await res.json();
        return data?.records?.[0]?.Id ?? null;
      } catch {
        return null;
      }
    }, objectApiName);
  }

}
